export const projects = [
  {
    slug: "online-admission-sdh",
    title: "Online Admission SDH",
    description:
      "The SDH online registration page allows prospective students to create an account, complete a detailed admissions form, make and confirm payments, upload required documents, and receive verification notifications via email/WhatsApp.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The Sekolah Dian Harapan (SDH) online registration portal guides users through a step-by-step enrollment process: starting with account creation and email verification, then logging in to complete personal and parental details, school history, and purchase a registration form. Payment is made through a secure payment gateway, which automatically verifies transactions. After successful payment, users receive both WhatsApp and email notifications, prompting them to complete an electronic form and upload supporting documents (such as a birth certificate, family card, report card, and photos), all within a secure system designed to streamline admissions for SDH’s 17 campuses across Indonesia.",
    features: [
      "Account creation via Sign Up (name, email, password)",
      "WhatsApp/Email verification link sent to activate account",
      "Secure login to access the registration dashboard",
      "Online form for student, parents, and school background information",
      "Purchase registration form through integrated payment gateway",
      "Automatic payment verification after successful transaction",
      "WhatsApp and Email notifications for payment and registration status",
      "Electronic form completion after payment confirmation",
      "Document upload for birth certificate, family card, report card, and photos",
      "Dashboard to track registration progress and submission status"
    ],      
    tools: [
      { name: "CodeIgniter", logo: "/codeigniter.png?height=40&width=40" },
      { name: "MySQL", logo: "/mysql.svg?height=40&width=40" },
      { name: "PHP", logo: "/php.png?height=40&width=40" },
    ],
    liveUrl: "https://sdh.or.id/registrasi/",
    githubUrl: "",
    timeline: "December 2022 - Present",
    categories: ["Web Development", "Enterprise Software"],
  },
  {
    slug: "ai-powered-analytics",
    title: "AI-Powered Analytics Dashboard",
    description:
      "An analytics platform that uses machine learning to provide predictive insights and anomaly detection.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The AI-Powered Analytics Dashboard leverages machine learning algorithms to transform raw data into actionable insights. It features predictive analytics, anomaly detection, and automated reporting capabilities, helping businesses make data-driven decisions faster and more accurately.",
    features: [
      "Real-time data processing",
      "Predictive analytics and forecasting",
      "Anomaly detection and alerts",
      "Customizable dashboards and reports",
      "Natural language query interface",
    ],
    tools: [
      { name: "Python", logo: "/placeholder.svg?height=40&width=40" },
      { name: "TensorFlow", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Vue.js", logo: "/placeholder.svg?height=40&width=40" },
      { name: "FastAPI", logo: "/placeholder.svg?height=40&width=40" },
      { name: "PostgreSQL", logo: "/placeholder.svg?height=40&width=40" },
    ],
    liveUrl: "https://example.com/analytics",
    githubUrl: "https://github.com/johndoe/ai-analytics",
    timeline: "Mar 2021 - Nov 2021",
    categories: ["Machine Learning", "Data Science", "Business Intelligence"],
  },
  {
    slug: "e-commerce-platform",
    title: "Modern E-Commerce Platform",
    description:
      "A full-featured e-commerce solution with headless architecture, supporting multiple storefronts and payment methods.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The Modern E-Commerce Platform is built with a headless architecture that separates the frontend and backend concerns, allowing for greater flexibility and customization. It supports multiple storefronts, payment methods, and shipping integrations, making it suitable for businesses of all sizes.",
    features: [
      "Headless architecture",
      "Multiple storefront support",
      "Advanced product search and filtering",
      "Integrated payment processing",
      "Inventory and order management",
      "Customer accounts and loyalty programs",
    ],
    tools: [
      { name: "Next.js", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Strapi", logo: "/placeholder.svg?height=40&width=40" },
      { name: "MongoDB", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Stripe", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Redis", logo: "/placeholder.svg?height=40&width=40" },
    ],
    liveUrl: "https://example.com/ecommerce",
    githubUrl: "https://github.com/johndoe/ecommerce",
    timeline: "Jun 2020 - Feb 2021",
    categories: ["E-Commerce", "Web Development", "Microservices"],
  },
  {
    slug: "mobile-fitness-app",
    title: "Mobile Fitness Application",
    description: "A cross-platform fitness app with workout tracking, nutrition planning, and social features.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The Mobile Fitness Application is designed to help users achieve their fitness goals through personalized workout plans, nutrition tracking, and social motivation. It features a clean, intuitive interface and syncs with popular fitness devices to provide a comprehensive health tracking experience.",
    features: [
      "Personalized workout plans",
      "Nutrition tracking and meal planning",
      "Progress tracking and analytics",
      "Social sharing and challenges",
      "Integration with fitness wearables",
    ],
    tools: [
      { name: "React Native", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Firebase", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Redux", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Node.js", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Express", logo: "/placeholder.svg?height=40&width=40" },
    ],
    liveUrl: "https://example.com/fitness-app",
    githubUrl: "https://github.com/johndoe/fitness-app",
    timeline: "Sep 2019 - May 2020",
    categories: ["Mobile Development", "Health & Fitness", "Social"],
  },
  {
    slug: "blockchain-voting-system",
    title: "Blockchain Voting System",
    description:
      "A secure and transparent voting system built on blockchain technology for organizations and governments.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The Blockchain Voting System leverages distributed ledger technology to create a secure, transparent, and tamper-proof voting platform. It addresses key challenges in electronic voting such as security, privacy, and verifiability, making it suitable for organizations, institutions, and potentially governments.",
    features: [
      "Secure voter authentication",
      "Anonymous yet verifiable voting",
      "Real-time results tabulation",
      "Immutable audit trail",
      "Resistance to tampering and fraud",
    ],
    tools: [
      { name: "Solidity", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Ethereum", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Web3.js", logo: "/placeholder.svg?height=40&width=40" },
      { name: "React", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Node.js", logo: "/placeholder.svg?height=40&width=40" },
    ],
    liveUrl: "https://example.com/blockchain-voting",
    githubUrl: "https://github.com/johndoe/blockchain-voting",
    timeline: "Jan 2019 - Aug 2019",
    categories: ["Blockchain", "Security", "Civic Tech"],
  },
  {
    slug: "smart-home-automation",
    title: "Smart Home Automation System",
    description:
      "An IoT-based home automation system that integrates with multiple smart home devices and provides a unified control interface.",
    thumbnail: "/placeholder.svg?height=600&width=800",
    gallery: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    content:
      "The Smart Home Automation System is an IoT platform that connects and controls various smart home devices through a single, intuitive interface. It supports voice commands, automated routines, and energy optimization, making homes more comfortable, efficient, and secure.",
    features: [
      "Unified control of multiple smart devices",
      "Voice control integration",
      "Automated routines and scenes",
      "Energy usage monitoring and optimization",
      "Remote access and control",
      "Security monitoring and alerts",
    ],
    tools: [
      { name: "Raspberry Pi", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Python", logo: "/placeholder.svg?height=40&width=40" },
      { name: "MQTT", logo: "/placeholder.svg?height=40&width=40" },
      { name: "React", logo: "/placeholder.svg?height=40&width=40" },
      { name: "Node-RED", logo: "/placeholder.svg?height=40&width=40" },
    ],
    liveUrl: "https://example.com/smart-home",
    githubUrl: "https://github.com/johndoe/smart-home",
    timeline: "Apr 2018 - Dec 2018",
    categories: ["IoT", "Smart Home", "Embedded Systems"],
  },
]
